[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/" }]
fuzz_runs = 10_000

auto_detect_remappings = true
remappings = [
    "forge-std/=lib/forge-std/src",
    "v4-core/=lib/v4-core/",
    "solmate/=lib/v4-core/lib/solmate/",
    "openzeppelin/=lib/v4-core/lib/v4-core/lib/openzeppelin-contracts/",
    "v4-periphery/=lib/v4-periphery/",
    "permit2/=lib/v4-periphery/lib/permit2/",
    "uniswap-hooks/=lib/uniswap-hooks/",
    
    # "@uniswap/v4-core/=lib/v4-periphery/lib/v4-core/",
    # "@openzeppelin/=lib/v4-periphery/lib/v4-core/lib/openzeppelin-contracts/",
    # "openzeppelin/=lib/v4-periphery/lib/v4-core/lib/openzeppelin-contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

